###
SELECT *, 
CASE WHEN PREV_START < ACTIVITY_START_TIME AND PREV_END < ACTIVITY_END_TIME AND PREV_END > ACTIVITY_START_TIME AND ACTIVITY <> 'Stiction' THEN PREV_END  
ELSE ACTIVITY_START_TIME END AS ACTIVITY_START_TIME_1, 
CASE WHEN NEXT_START > ACTIVITY_START_TIME AND NEXT_START < ACTIVITY_END_TIME AND NEXT_END > ACTIVITY_END_TIME AND ACTIVITY <> 'Stiction' THEN NEXT_START ELSE ACTIVITY_END_TIME END AS ACTIVITY_END_TIME_1  FROM
(SELECT * EXCEPT(ACTIVITY_DURATION_SEC,ACTIVITY_DURATION_MIN,ACTIVITY_DURATION_HR, STUDY_WEEK,ALGORITHM_VERSION, STUDY_NAME,GEN_UUID ), 
LEAD(ACTIVITY_START_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_START_TIME) AS NEXT_START, 
LEAD(ACTIVITY_END_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_START_TIME) AS NEXT_END,
 LAG(ACTIVITY_START_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_START_TIME) AS PREV_START,
  LAG(ACTIVITY_END_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_START_TIME) AS PREV_END
 FROM (SELECT * FROM `ct-wearables-analytical-pf.HPN_WAP_STAGING.STG_AP_PET_ACTIVITY_DATA_3706`
WHERE ACTIVITY_DAY = "2020-02-24") A )
ORDER BY ACTIVITY_START_TIME, ACTIVITY_END_TIME; 



WITH PARTIAL_OVERLAPS_1 AS (
  SELECT
     * EXCEPT(ACTIVITY_DURATION_SEC,ACTIVITY_DURATION_MIN,ACTIVITY_DURATION_HR, STUDY_WEEK,ALGORITHM_VERSION, STUDY_NAME,GEN_UUID ),
    LEAD(ACTIVITY_START_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_START_TIME) AS NEXT_START,
    LEAD(ACTIVITY_END_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_START_TIME) AS NEXT_END,
    LAG(ACTIVITY_START_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_START_TIME) AS PREV_START,
    LAG(ACTIVITY_END_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_START_TIME) AS PREV_END
  FROM `ct-wearables-analytical-pf.HPN_WAP_STAGING.STG_AP_PET_ACTIVITY_DATA_3706`
  WHERE ACTIVITY_DAY = "2020-02-24"
) 
, PARTIAL_OVERLAPS_2 AS (
SELECT
  * EXCEPT(NEXT_START,NEXT_END,PREV_START,PREV_END,ACTIVITY_START_TIME,ACTIVITY_END_TIME),
  CASE
    WHEN PREV_START < ACTIVITY_START_TIME AND PREV_END < ACTIVITY_END_TIME AND PREV_END > ACTIVITY_START_TIME AND ACTIVITY <> 'Stiction' THEN PREV_END
    ELSE ACTIVITY_START_TIME
  END AS ACTIVITY_START_TIME,
  CASE
    WHEN NEXT_START > ACTIVITY_START_TIME AND NEXT_START < ACTIVITY_END_TIME AND NEXT_END > ACTIVITY_END_TIME AND ACTIVITY <> 'Stiction' THEN NEXT_START
    ELSE ACTIVITY_END_TIME
  END AS ACTIVITY_END_TIME
FROM PARTIAL_OVERLAPS_1)
, PARTIAL_OVERLAPS_3 AS(
 SELECT
     * ,
    LEAD(ACTIVITY_START_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_END_TIME) AS NEXT_START,
    LEAD(ACTIVITY_END_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_END_TIME) AS NEXT_END,
    LAG(ACTIVITY_START_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_END_TIME) AS PREV_START,
    LAG(ACTIVITY_END_TIME) OVER(PARTITION BY "PET_ID", "DEVICE_ID", "ALGORITHM_MASTER_ID", "STUDY_ID" ORDER BY ACTIVITY_END_TIME) AS PREV_END
    FROM PARTIAL_OVERLAPS_2), 
    PARTIAL_OVERLAPS_FINAL AS (
    SELECT
  * EXCEPT(NEXT_START,NEXT_END,PREV_START,PREV_END,ACTIVITY_START_TIME,ACTIVITY_END_TIME),
  CASE
    WHEN PREV_START < ACTIVITY_START_TIME AND PREV_END < ACTIVITY_END_TIME AND PREV_END > ACTIVITY_START_TIME AND ACTIVITY <> 'Stiction' THEN PREV_END
    ELSE ACTIVITY_START_TIME
  END AS ACTIVITY_START_TIME,
  CASE
    WHEN NEXT_START > ACTIVITY_START_TIME AND NEXT_START < ACTIVITY_END_TIME AND NEXT_END > ACTIVITY_END_TIME AND ACTIVITY <> 'Stiction' THEN NEXT_START
    ELSE ACTIVITY_END_TIME
  END AS ACTIVITY_END_TIME
FROM PARTIAL_OVERLAPS_3) 
, COMPLETE_EXACT_OVERLAPS AS (
   SELECT *EXCEPT(IS_VALID)  FROM (
SELECT *, CASE WHEN (ACTIVITY_START_TIME < PREV_MAX_END_TIME AND ACTIVITY_END_TIME < PREV_MAX_END_TIME) OR ACTIVITY_END_TIME <= PREV_MAX_END_TIME THEN 0 ELSE 1 END AS IS_VALID FROM
(SELECT *, MAX(ACTIVITY_END_TIME) OVER (PARTITION BY PET_ID, DEVICE_ID, STUDY_ID, ALGORITHM_MASTER_ID ORDER BY ACTIVITY_START_TIME, ACTIVITY_END_TIME DESC, CASE WHEN ACTIVITY = 'Stiction' THEN 1 ELSE 0 END DESC ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS PREV_MAX_END_TIME
 FROM PARTIAL_OVERLAPS_FINAL))
  WHERE IS_VALID = 1)
SELECT * FROM COMPLETE_EXACT_OVERLAPS 
ORDER BY ACTIVITY_START_TIME, ACTIVITY_END_TIME;
